version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - automerge
  target-branch: "r-confluence"
